from tkinter import *
from tkinter import messagebox
import tkinter.messagebox
from tkinter import *
import stdDatabase_Backend
from datetime import datetime
import tkinter as tk



class Contact():

    def __init__(self, root):

        self.root = root
        self.root.title("Contact Storage")
        self.root.geometry("1635x653+0+0")
        self.root.config(bg="#d4f1ff")
        root.resizable(width=False, height=False)

        fname = StringVar()  #First Name
        mname = StringVar()  #Middle Name
        lname = StringVar()  #Last Name
        mail = StringVar()  #Email
        mnumber = StringVar()  #Mobile Number
        wnumber = StringVar()  #Work Number
        dob = StringVar() #Birthday


        #Function





        def iExit():
            iExit = tkinter.messagebox.askyesno("Contact Storage","Would you like to exit?")
            if iExit > 0:
                root.destroy()
                return

        def clearData():
            self.txtfname.delete(0, END)
            self.txtmname.delete(0, END)
            self.txtlname.delete(0, END)
            self.txtmail.delete(0, END)
            self.txtmnumber.delete(0, END)
            self.txtwnumber.delete(0, END)
            self.txtbir.delete(0, END)

        def addData():
            if(len(fname.get()) !=0):
                stdDatabase_Backend.addConRec(fname.get(), mname.get(), lname.get(), mail.get(), mnumber.get(),
                                     wnumber.get(), dob.get())
                contactData.delete(0, END)
                contactData.insert(END,(fname.get(), mname.get(), lname.get(), mail.get(), mnumber.get(),
                                     wnumber.get(), dob.get()))



        def DisplayData():
            contactData.delete(0,END)
            for row in stdDatabase_Backend.viewDate():
                contactData.insert(END,row,str(""))

        def ContactRec(event):
            global sd
            searchfname = contactData.curselection()[0]
            sd = contactData.get(searchfname)

            self.txtfname.delete(0, END)
            self.txtfname.insert(END,sd[1])
            self.txtmname.delete(0, END)
            self.txtmname.insert(END, sd[2])
            self.txtlname.delete(0, END)
            self.txtlname.insert(END, sd[3])
            self.txtmail.delete(0, END)
            self.txtmail.insert(END, sd[4])
            self.txtmnumber.delete(0, END)
            self.txtmnumber.insert(END, sd[5])
            self.txtwnumber.delete(0, END)
            self.txtwnumber.insert(END, sd[6])
            self.txtbir.delete(0, END)
            self.txtbir.insert(END, sd[7])


        def DeleteDate():
            if(len(fname.get()) !=0):
                stdDatabase_Backend.deleteRec(sd[0])
                clearData()
                DisplayData()


        def update():
            if(len(fname.get()) !=0):
                stdDatabase_Backend.deleteRec(sd[0])
            if(len(fname.get()) !=0):
                stdDatabase_Backend.addConRec(fname.get(), mname.get(), lname.get(), mail.get(), mnumber.get(),
                                     wnumber.get(), dob.get())
                contactData.delete(0,END)
                contactData.insert(END,(fname.get(), mname.get(), lname.get(), mail.get(), mnumber.get(),
                                     wnumber.get(), dob.get()))




        def popupmsgback():
            popupmsgback = tk.Tk()

            def Backcya():
                MainFrame.config(bg='cyan')
                self.root.config(bg='cyan')
                DataFrame.config(bg='cyan')
                ButtonFrame.config(bg='cyan')
                DataFrameRight.config(bg='cyan')
                self.btnAddDate.config(bg='cyan')
                self.btnClear.config(bg='cyan')
                self.btnDelete.config(bg='cyan')
                self.btnDisplay.config(bg='cyan')
                self.btnExit.config(bg='cyan')
                self.btnUpdate.config(bg='cyan')
                btnBack.config(bg='cyan')
                btnTxt.config(bg='cyan')
                self.lblTit.config(bg='cyan')
                DataFrameLEFT.config(bg='cyan')
                self.lblfname.config(bg='cyan')
                self.txtfname.config(bg='cyan')
                self.lblmname.config(bg='cyan')
                self.txtmname.config(bg='cyan')
                self.lbllname.config(bg='cyan')
                self.txtlname.config(bg='cyan')
                self.lblmail.config(bg='cyan')
                self.txtmail.config(bg='cyan')
                self.lblmnumber.config(bg='cyan')
                self.txtmnumber.config(bg='cyan')
                self.lblwnumber.config(bg='cyan')
                self.txtwnumber.config(bg='cyan')
                self.lblbir.config(bg='cyan')
                self.txtbir.config(bg='cyan')
                contactData.config(bg='cyan')
                TitFrame.config(bg="cyan")


            def BackBlue():
                MainFrame.config(bg='Light Blue')
                self.root.config(bg='Light Blue')
                DataFrame.config(bg='Light Blue')
                ButtonFrame.config(bg='Light Blue')
                DataFrameRight.config(bg='Light Blue')
                self.btnAddDate.config(bg='Light Blue')
                self.btnClear.config(bg='Light Blue')
                self.btnDelete.config(bg='Light Blue')
                self.btnDisplay.config(bg='Light Blue')
                self.btnExit.config(bg='Light Blue')
                self.btnUpdate.config(bg='Light Blue')
                btnBack.config(bg='Light Blue')
                btnTxt.config(bg='Light Blue')
                self.lblTit.config(bg='Light Blue')
                DataFrameLEFT.config(bg='Light Blue')
                self.lblfname.config(bg='Light Blue')
                self.txtfname.config(bg='Light Blue')
                self.lblmname.config(bg='Light Blue')
                self.txtmname.config(bg='Light Blue')
                self.lbllname.config(bg='Light Blue')
                self.txtlname.config(bg='Light Blue')
                self.lblmail.config(bg='Light Blue')
                self.txtmail.config(bg='Light Blue')
                self.lblmnumber.config(bg='Light Blue')
                self.txtmnumber.config(bg='Light Blue')
                self.lblwnumber.config(bg='Light Blue')
                self.txtwnumber.config(bg='Light Blue')
                self.lblbir.config(bg='Light Blue')
                self.txtbir.config(bg='Light Blue')
                contactData.config(bg='Light Blue')
                TitFrame.config(bg="Light Blue")

            def BackDBlue():
                MainFrame.config(bg='Dark Blue')
                self.root.config(bg='Dark Blue')
                DataFrame.config(bg='Dark Blue')
                ButtonFrame.config(bg='Dark Blue')
                DataFrameRight.config(bg='Dark Blue')
                self.btnAddDate.config(bg='Dark Blue')
                self.btnClear.config(bg='Dark Blue')
                self.btnDelete.config(bg='Dark Blue')
                self.btnDisplay.config(bg='Dark Blue')
                self.btnExit.config(bg='Dark Blue')
                self.btnUpdate.config(bg='Dark Blue')
                btnBack.config(bg='Dark Blue')
                btnTxt.config(bg='Dark Blue')
                self.lblTit.config(bg='Dark Blue')
                DataFrameLEFT.config(bg='Dark Blue')
                self.lblfname.config(bg='Dark Blue')
                self.txtfname.config(bg='Dark Blue')
                self.lblmname.config(bg='Dark Blue')
                self.txtmname.config(bg='Dark Blue')
                self.lbllname.config(bg='Dark Blue')
                self.txtlname.config(bg='Dark Blue')
                self.lblmail.config(bg='Dark Blue')
                self.txtmail.config(bg='Dark Blue')
                self.lblmnumber.config(bg='Dark Blue')
                self.txtmnumber.config(bg='Dark Blue')
                self.lblwnumber.config(bg='Dark Blue')
                self.txtwnumber.config(bg='Dark Blue')
                self.lblbir.config(bg='Dark Blue')
                self.txtbir.config(bg='Dark Blue')
                contactData.config(bg='Dark Blue')
                TitFrame.config(bg="Dark Blue")
                MainFrame.config(bg='Dark Blue')
                TitFrame.config(bg='Dark Blue')
                self.root.config(bg='Dark Blue')
                DataFrame.config(bg='Dark Blue')
                ButtonFrame.config(bg='Dark Blue')

            def TxtRed():
                self.lblfname.config(bg='red')
                self.txtfname.config(bg='red')
                self.lblmname.config(bg='red')
                self.txtmname.config(bg='red')
                self.lbllname.config(bg='red')
                self.txtlname.config(bg='red')
                self.lblmail.config(bg='red')
                self.txtmail.config(bg='red')
                self.lblmnumber.config(bg='red')
                self.txtmnumber.config(bg='red')
                self.lblwnumber.config(bg='red')
                self.txtwnumber.config(bg='red')
                self.lblbir.config(bg='red')
                self.txtbir.config(bg='red')
                DataFrameRight.config(bg='red')
                self.btnAddDate.config(bg='red')
                self.btnClear.config(bg='red')
                self.btnDelete.config(bg='red')
                self.btnDisplay.config(bg='red')
                self.btnExit.config(bg='red')
                self.btnUpdate.config(bg='red')
                btnBack.config(bg='red')
                btnTxt.config(bg='red')
                self.lblTit.config(bg='red')
                DataFrameLEFT.config(bg='red')
                DataFrameRight.config(bg='red')
                self.btnAddDate.config(bg='red')
                self.btnClear.config(bg='red')
                self.btnDelete.config(bg='red')
                self.btnDisplay.config(bg='red')
                self.btnExit.config(bg='red')
                self.btnUpdate.config(bg='red')
                btnBack.config(bg='red')
                btnTxt.config(bg='red')
                contactData.config(bg='red')
                MainFrame.config(bg='red')
                TitFrame.config(bg='red')
                self.root.config(bg='red')
                DataFrame.config(bg='red')
                ButtonFrame.config(bg='red')

            def bckgre():
                self.lblfname.config(bg='green')
                self.txtfname.config(bg='green')
                self.lblmname.config(bg='green')
                self.txtmname.config(bg='green')
                self.lbllname.config(bg='green')
                self.txtlname.config(bg='green')
                self.lblmail.config(bg='green')
                self.txtmail.config(bg='green')
                self.lblmnumber.config(bg='green')
                self.txtmnumber.config(bg='green')
                self.lblwnumber.config(bg='green')
                self.txtwnumber.config(bg='green')
                self.lblbir.config(bg='green')
                self.txtbir.config(bg='green')
                DataFrameRight.config(bg='green')
                self.btnAddDate.config(bg='green')
                self.btnClear.config(bg='green')
                self.btnDelete.config(bg='green')
                self.btnDisplay.config(bg='green')
                self.btnExit.config(bg='green')
                self.btnUpdate.config(bg='green')
                btnBack.config(bg='green')
                btnTxt.config(bg='green')
                self.lblTit.config(bg='green')
                DataFrameLEFT.config(bg='green')
                DataFrameRight.config(bg='green')
                self.btnAddDate.config(bg='green')
                self.btnClear.config(bg='green')
                self.btnDelete.config(bg='green')
                self.btnDisplay.config(bg='green')
                self.btnExit.config(bg='green')
                self.btnUpdate.config(bg='green')
                btnTxt.config(bg='green')
                MainFrame.config(bg='green')
                TitFrame.config(bg='green')
                self.root.config(bg='green')
                DataFrame.config(bg='green')
                ButtonFrame.config(bg='green')
                contactData.config(bg='green')




            def bckyel():

                self.lblfname.config(bg='Yellow')
                self.txtfname.config(bg='Yellow')
                self.lblmname.config(bg='Yellow')
                self.txtmname.config(bg='Yellow')
                self.lbllname.config(bg='Yellow')
                self.txtlname.config(bg='Yellow')
                self.lblmail.config(bg='Yellow')
                self.txtmail.config(bg='Yellow')
                self.lblmnumber.config(bg='Yellow')
                self.txtmnumber.config(bg='Yellow')
                self.lblwnumber.config(bg='Yellow')
                self.txtwnumber.config(bg='Yellow')
                self.lblbir.config(bg='Yellow')
                self.txtbir.config(bg='Yellow')
                DataFrameRight.config(bg='Yellow')
                self.btnAddDate.config(bg='Yellow')
                self.btnClear.config(bg='Yellow')
                self.btnDelete.config(bg='Yellow')
                self.btnDisplay.config(bg='Yellow')
                self.btnExit.config(bg='Yellow')
                self.btnUpdate.config(bg='Yellow')
                btnBack.config(bg='Yellow')
                btnTxt.config(bg='Yellow')
                self.lblTit.config(bg='Yellow')
                DataFrameLEFT.config(bg='Yellow')
                self.btnAddDate.config(bg='Yellow')
                self.btnExit.config(bg='Yellow')
                self.btnUpdate.config(bg='Yellow')
                btnBack.config(bg='Yellow')
                btnTxt.config(bg='Yellow')
                contactData.config(bg='Yellow')
                MainFrame.config(bg='Yellow')
                TitFrame.config(bg='Yellow')
                self.root.config(bg='Yellow')
                DataFrame.config(bg='Yellow')
                ButtonFrame.config(bg='Yellow')

            def bckOr():
                self.lblfname.config(bg='Orange')
                self.txtfname.config(bg='Orange')
                self.lblmname.config(bg='Orange')
                self.txtmname.config(bg='Orange')
                self.lbllname.config(bg='Orange')
                self.txtlname.config(bg='Orange')
                self.lblmail.config(bg='Orange')
                self.txtmail.config(bg='Orange')
                self.lblmnumber.config(bg='Orange')
                self.txtmnumber.config(bg='Orange')
                self.lblwnumber.config(bg='Orange')
                self.txtwnumber.config(bg='Orange')
                self.lblbir.config(bg='Orange')
                self.txtbir.config(bg='Orange')
                DataFrameRight.config(bg='Orange')
                self.btnAddDate.config(bg='Orange')
                self.btnClear.config(bg='Orange')
                self.btnDelete.config(bg='Orange')
                self.btnDisplay.config(bg='Orange')
                self.btnExit.config(bg='Orange')
                self.btnUpdate.config(bg='Orange')
                btnBack.config(bg='Orange')
                btnTxt.config(bg='Orange')
                self.lblTit.config(bg='Orange')
                DataFrameLEFT.config(bg='Orange')
                DataFrameRight.config(bg='Orange')
                self.btnAddDate.config(bg='Orange')
                self.btnClear.config(bg='Orange')
                self.btnDelete.config(bg='Orange')
                self.btnDisplay.config(bg='Orange')
                self.btnExit.config(bg='Orange')
                self.btnUpdate.config(bg='Orange')
                btnBack.config(bg='Orange')
                btnTxt.config(bg='Orange')
                contactData.config(bg='Orange')
                MainFrame.config(bg='Orange')
                TitFrame.config(bg='Orange')
                self.root.config(bg='Orange')
                DataFrame.config(bg='Orange')
                ButtonFrame.config(bg='Orange')

            def bcklblu():
                self.lblfname.config(bg='Light Blue')
                self.txtfname.config(bg='Light Blue')
                self.lblmname.config(bg='Light Blue')
                self.txtmname.config(bg='Light Blue')
                self.lbllname.config(bg='Light Blue')
                self.txtlname.config(bg='Light Blue')
                self.lblmail.config(bg='Light Blue')
                self.txtmail.config(bg='Light Blue')
                self.lblmnumber.config(bg='Light Blue')
                self.txtmnumber.config(bg='Light Blue')
                self.lblwnumber.config(bg='Light Blue')
                self.txtwnumber.config(bg='Light Blue')
                self.lblbir.config(bg='Light Blue')
                self.txtbir.config(bg='Light Blue')
                DataFrameRight.config(bg='Light Blue')
                self.btnAddDate.config(bg='Light Blue')
                self.btnClear.config(bg='Light Blue')
                self.btnDelete.config(bg='Light Blue')
                self.btnDisplay.config(bg='Light Blue')
                self.btnExit.config(bg='Light Blue')
                self.btnUpdate.config(bg='Light Blue')
                btnBack.config(bg='Light Blue')
                btnTxt.config(bg='Light Blue')
                self.lblTit.config(bg='Light Blue')
                DataFrameLEFT.config(bg='Light Blue')
                DataFrameRight.config(bg='Light Blue')
                self.btnAddDate.config(bg='Light Blue')
                self.btnClear.config(bg='Light Blue')
                self.btnDelete.config(bg='Light Blue')
                self.btnDisplay.config(bg='Light Blue')
                self.btnExit.config(bg='Light Blue')
                self.btnUpdate.config(bg='Light Blue')
                btnBack.config(bg='Light Blue')
                btnTxt.config(bg='Light Blue')
                contactData.config(bg='Light Blue')
                MainFrame.config(bg='Light Blue')
                TitFrame.config(bg='Light Blue')
                self.root.config(bg='Light Blue')
                DataFrame.config(bg='Light Blue')
                ButtonFrame.config(bg='Light Blue')


            def bckxblue():
                self.lblfname.config(bg='Blue')
                self.txtfname.config(bg='Blue')
                self.lblmname.config(bg='Blue')
                self.txtmname.config(bg='Blue')
                self.lbllname.config(bg='Blue')
                self.txtlname.config(bg='Blue')
                self.lblmail.config(bg='Blue')
                self.txtmail.config(bg='Blue')
                self.lblmnumber.config(bg='Blue')
                self.txtmnumber.config(bg='Blue')
                self.lblwnumber.config(bg='Blue')
                self.txtwnumber.config(bg='Blue')
                self.lblbir.config(bg='Blue')
                self.txtbir.config(bg='Blue')
                DataFrameRight.config(bg='Blue')
                self.btnAddDate.config(bg='Blue')
                self.btnClear.config(bg='Blue')
                self.btnDelete.config(bg='Blue')
                self.btnDisplay.config(bg='Blue')
                self.btnExit.config(bg='Blue')
                self.btnUpdate.config(bg='Blue')
                btnBack.config(bg='Blue')
                btnTxt.config(bg='Blue')
                self.lblTit.config(bg='Blue')
                DataFrameLEFT.config(bg='Blue')
                DataFrameRight.config(bg='Blue')
                self.btnAddDate.config(bg='Blue')
                self.btnClear.config(bg='Blue')
                self.btnDelete.config(bg='Blue')
                self.btnDisplay.config(bg='Blue')
                self.btnExit.config(bg='Blue')
                self.btnUpdate.config(bg='Blue')
                btnBack.config(bg='Blue')
                btnTxt.config(bg='Blue')
                contactData.config(bg='Blue')
                MainFrame.config(bg='Blue')
                TitFrame.config(bg='Blue')
                self.root.config(bg='Blue')
                DataFrame.config(bg='Blue')
                ButtonFrame.config(bg='Blue')

            def bckdblue():
                self.lblfname.config(bg='Dark Blue')
                self.txtfname.config(bg='Dark Blue')
                self.lblmname.config(bg='Dark Blue')
                self.txtmname.config(bg='Dark Blue')
                self.lbllname.config(bg='Dark Blue')
                self.txtlname.config(bg='Dark Blue')
                self.lblmail.config(bg='Dark Blue')
                self.txtmail.config(bg='Dark Blue')
                self.lblmnumber.config(bg='Dark Blue')
                self.txtmnumber.config(bg='Dark Blue')
                self.lblwnumber.config(bg='Dark Blue')
                self.txtwnumber.config(bg='Dark Blue')
                self.lblbir.config(bg='Dark Blue')
                self.txtbir.config(bg='Dark Blue')
                DataFrameRight.config(bg='Dark Blue')
                self.btnAddDate.config(bg='Dark Blue')
                self.btnClear.config(bg='Dark Blue')
                self.btnDelete.config(bg='Dark Blue')
                self.btnDisplay.config(bg='Dark Blue')
                self.btnExit.config(bg='Dark Blue')
                self.btnUpdate.config(bg='Dark Blue')
                btnBack.config(bg='Dark Blue')
                btnTxt.config(bg='Dark Blue')
                self.lblTit.config(bg='Dark Blue')
                DataFrameLEFT.config(bg='Dark Blue')
                DataFrameRight.config(bg='Dark Blue')
                self.btnAddDate.config(bg='Dark Blue')
                self.btnClear.config(bg='Dark Blue')
                self.btnDelete.config(bg='Dark Blue')
                self.btnDisplay.config(bg='Dark Blue')
                self.btnExit.config(bg='Dark Blue')
                self.btnUpdate.config(bg='Dark Blue')
                btnBack.config(bg='Dark Blue')
                btnTxt.config(bg='Dark Blue')
                contactData.config(bg='Dark Blue')
                MainFrame.config(bg='Dark Blue')
                TitFrame.config(bg='Dark Blue')
                self.root.config(bg='Dark Blue')
                DataFrame.config(bg='Dark Blue')
                ButtonFrame.config(bg='Dark Blue')

            def bckvio():
                self.lblfname.config(bg='Violet')
                self.txtfname.config(bg='Violet')
                self.lblmname.config(bg='Violet')
                self.txtmname.config(bg='Violet')
                self.lbllname.config(bg='Violet')
                self.txtlname.config(bg='Violet')
                self.lblmail.config(bg='Violet')
                self.txtmail.config(bg='Violet')
                self.lblmnumber.config(bg='Violet')
                self.txtmnumber.config(bg='Violet')
                self.lblwnumber.config(bg='Violet')
                self.txtwnumber.config(bg='Violet')
                self.lblbir.config(bg='Violet')
                self.txtbir.config(bg='Violet')
                DataFrameRight.config(bg='Violet')
                self.btnAddDate.config(bg='Violet')
                self.btnClear.config(bg='Violet')
                self.btnDelete.config(bg='Violet')
                self.btnDisplay.config(bg='Violet')
                self.btnExit.config(bg='Violet')
                self.btnUpdate.config(bg='Violet')
                btnBack.config(bg='Violet')
                btnTxt.config(bg='Violet')
                self.lblTit.config(bg='Violet')
                DataFrameLEFT.config(bg='Violet')
                DataFrameRight.config(bg='Violet')
                self.btnAddDate.config(bg='Violet')
                self.btnClear.config(bg='Violet')
                self.btnDelete.config(bg='Violet')
                self.btnDisplay.config(bg='Violet')
                self.btnExit.config(bg='Violet')
                self.btnUpdate.config(bg='Violet')
                btnBack.config(bg='Violet')
                btnTxt.config(bg='Violet')
                contactData.config(bg='Violet')
                MainFrame.config(bg='Violet')
                TitFrame.config(bg='Violet')
                self.root.config(bg='Violet')
                DataFrame.config(bg='Violet')
                ButtonFrame.config(bg='Violet')

            def bckmag():
                self.lblfname.config(bg='Magenta')
                self.txtfname.config(bg='Magenta')
                self.lblmname.config(bg='Magenta')
                self.txtmname.config(bg='Magenta')
                self.lbllname.config(bg='Magenta')
                self.txtlname.config(bg='Magenta')
                self.lblmail.config(bg='Magenta')
                self.txtmail.config(bg='Magenta')
                self.lblmnumber.config(bg='Magenta')
                self.txtmnumber.config(bg='Magenta')
                self.lblwnumber.config(bg='Magenta')
                self.txtwnumber.config(bg='Magenta')
                self.lblbir.config(bg='Magenta')
                self.txtbir.config(bg='Magenta')
                DataFrameRight.config(bg='Magenta')
                self.btnAddDate.config(bg='Magenta')
                self.btnClear.config(bg='Magenta')
                self.btnDelete.config(bg='Magenta')
                self.btnDisplay.config(bg='Magenta')
                self.btnExit.config(bg='Magenta')
                self.btnUpdate.config(bg='Magenta')
                btnBack.config(bg='Magenta')
                btnTxt.config(bg='Magenta')
                self.lblTit.config(bg='Magenta')
                DataFrameLEFT.config(bg='Magenta')
                DataFrameRight.config(bg='Magenta')
                self.btnAddDate.config(bg='Magenta')
                self.btnClear.config(bg='Magenta')
                self.btnDelete.config(bg='Magenta')
                self.btnDisplay.config(bg='Magenta')
                self.btnExit.config(bg='Magenta')
                self.btnUpdate.config(bg='Magenta')
                btnBack.config(bg='Magenta')
                btnTxt.config(bg='Magenta')
                contactData.config(bg='Magenta')
                MainFrame.config(bg='Magenta')
                TitFrame.config(bg='Magenta')
                self.root.config(bg='Magenta')
                DataFrame.config(bg='Magenta')
                ButtonFrame.config(bg='Magenta')


            def bckxpurp():
                self.lblfname.config(bg='Purple')
                self.txtfname.config(bg='Purple')
                self.lblmname.config(bg='Purple')
                self.txtmname.config(bg='Purple')
                self.lbllname.config(bg='Purple')
                self.txtlname.config(bg='Purple')
                self.lblmail.config(bg='Purple')
                self.txtmail.config(bg='Purple')
                self.lblmnumber.config(bg='Purple')
                self.txtmnumber.config(bg='Purple')
                self.lblwnumber.config(bg='Purple')
                self.txtwnumber.config(bg='Purple')
                self.lblbir.config(bg='Purple')
                self.txtbir.config(bg='Purple')
                DataFrameRight.config(bg='Purple')
                self.btnAddDate.config(bg='Purple')
                self.btnClear.config(bg='Purple')
                self.btnDelete.config(bg='Purple')
                self.btnDisplay.config(bg='Purple')
                self.btnExit.config(bg='Purple')
                self.btnUpdate.config(bg='Purple')
                btnBack.config(bg='Purple')
                btnTxt.config(bg='Purple')
                self.lblTit.config(bg='Purple')
                DataFrameLEFT.config(bg='Purple')
                DataFrameRight.config(bg='Purple')
                self.btnAddDate.config(bg='Purple')
                self.btnClear.config(bg='Purple')
                self.btnDelete.config(bg='Purple')
                self.btnDisplay.config(bg='Purple')
                self.btnExit.config(bg='Purple')
                self.btnUpdate.config(bg='Purple')
                btnBack.config(bg='Purple')
                btnTxt.config(bg='Purple')
                contactData.config(bg='Purple')
                MainFrame.config(bg='Purple')
                TitFrame.config(bg='Purple')
                self.root.config(bg='Purple')
                DataFrame.config(bg='Purple')
                ButtonFrame.config(bg='Purple')

            def bcklgry():
                self.lblfname.config(bg='Light Grey')
                self.txtfname.config(bg='Light Grey')
                self.lblmname.config(bg='Light Grey')
                self.txtmname.config(bg='Light Grey')
                self.lbllname.config(bg='Light Grey')
                self.txtlname.config(bg='Light Grey')
                self.lblmail.config(bg='Light Grey')
                self.txtmail.config(bg='Light Grey')
                self.lblmnumber.config(bg='Light Grey')
                self.txtmnumber.config(bg='Light Grey')
                self.lblwnumber.config(bg='Light Grey')
                self.txtwnumber.config(bg='Light Grey')
                self.lblbir.config(bg='Light Grey')
                self.txtbir.config(bg='Light Grey')
                DataFrameRight.config(bg='Light Grey')
                self.btnAddDate.config(bg='Light Grey')
                self.btnClear.config(bg='Light Grey')
                self.btnDelete.config(bg='Light Grey')
                self.btnDisplay.config(bg='Light Grey')
                self.btnExit.config(bg='Light Grey')
                self.btnUpdate.config(bg='Light Grey')
                btnBack.config(bg='Light Grey')
                btnTxt.config(bg='Light Grey')
                self.lblTit.config(bg='Light Grey')
                DataFrameLEFT.config(bg='Light Grey')
                DataFrameRight.config(bg='Light Grey')
                self.btnAddDate.config(bg='Light Grey')
                self.btnClear.config(bg='Light Grey')
                self.btnDelete.config(bg='Light Grey')
                self.btnDisplay.config(bg='Light Grey')
                self.btnExit.config(bg='Light Grey')
                self.btnUpdate.config(bg='Light Grey')
                btnBack.config(bg='Light Grey')
                btnTxt.config(bg='Light Grey')
                contactData.config(bg='Light Grey')
                MainFrame.config(bg='Light Grey')
                TitFrame.config(bg='Light Grey')
                self.root.config(bg='Light grey')
                DataFrame.config(bg='Light Grey')
                ButtonFrame.config(bg='Light Grey')

            def bckgry():
                self.lblfname.config(bg='Grey')
                self.txtfname.config(bg='Grey')
                self.lblmname.config(bg='Grey')
                self.txtmname.config(bg='Grey')
                self.lbllname.config(bg='Grey')
                self.txtlname.config(bg='Grey')
                self.lblmail.config(bg='Grey')
                self.txtmail.config(bg='Grey')
                self.lblmnumber.config(bg='Grey')
                self.txtmnumber.config(bg='Grey')
                self.lblwnumber.config(bg='Grey')
                self.txtwnumber.config(bg='Grey')
                self.lblbir.config(bg='Grey')
                self.txtbir.config(bg='Grey')
                DataFrameRight.config(bg='Grey')
                self.btnAddDate.config(bg='Grey')
                self.btnClear.config(bg='Grey')
                self.btnDelete.config(bg='Grey')
                self.btnDisplay.config(bg='Grey')
                self.btnExit.config(bg='Grey')
                self.btnUpdate.config(bg='Grey')
                btnBack.config(bg='Grey')
                btnTxt.config(bg='Grey')
                self.lblTit.config(bg='Grey')
                DataFrameLEFT.config(bg='Grey')
                DataFrameRight.config(bg='Grey')
                self.btnAddDate.config(bg='Grey')
                self.btnClear.config(bg='Grey')
                self.btnDelete.config(bg='Grey')
                self.btnDisplay.config(bg='Grey')
                self.btnExit.config(bg='Grey')
                self.btnUpdate.config(bg='Grey')
                btnBack.config(bg='Grey')
                btnTxt.config(bg='Grey')
                contactData.config(bg='Grey')
                MainFrame.config(bg='Grey')
                TitFrame.config(bg='Grey')
                self.root.config(bg='grey')
                DataFrame.config(bg='Grey')
                ButtonFrame.config(bg='Grey')

            def bckdgray():
                MainFrame.config(bg='Dark Grey')
                TitFrame.config(bg='Dark Grey')
                self.root.config(bg='Dark grey')
                DataFrame.config(bg='Dark Grey')
                ButtonFrame.config(bg='Dark Grey')
                self.lblfname.config(bg='Dark Grey')
                self.txtfname.config(bg='Dark Grey')
                self.lblmname.config(bg='Dark Grey')
                self.txtmname.config(bg='Dark Grey')
                self.lbllname.config(bg='Dark Grey')
                self.txtlname.config(bg='Dark Grey')
                self.lblmail.config(bg='Dark Grey')
                self.txtmail.config(bg='Dark Grey')
                self.lblmnumber.config(bg='Dark Grey')
                self.txtmnumber.config(bg='Dark Grey')
                self.lblwnumber.config(bg='Dark Grey')
                self.txtwnumber.config(bg='Dark Grey')
                self.lblbir.config(bg='Dark Grey')
                self.txtbir.config(bg='Dark Grey')
                DataFrameRight.config(bg='Dark Grey')
                self.btnAddDate.config(bg='Dark Grey')
                self.btnClear.config(bg='Dark Grey')
                self.btnDelete.config(bg='Dark Grey')
                self.btnDisplay.config(bg='Dark Grey')
                self.btnExit.config(bg='Dark Grey')
                self.btnUpdate.config(bg='Dark Grey')
                btnBack.config(bg='Dark Grey')
                btnTxt.config(bg='Dark Grey')
                self.lblTit.config(bg='Dark Grey')
                DataFrameLEFT.config(bg='Dark Grey')
                DataFrameRight.config(bg='Dark Grey')
                self.btnAddDate.config(bg='Dark Grey')
                self.btnClear.config(bg='Dark Grey')
                self.btnDelete.config(bg='Dark Grey')
                self.btnDisplay.config(bg='Dark Grey')
                self.btnExit.config(bg='Dark Grey')
                self.btnUpdate.config(bg='Dark Grey')
                btnBack.config(bg='Dark Grey')
                btnTxt.config(bg='Dark Grey')
                contactData.config(bg='Dark Grey')

            def bcke1():
                MainFrame.config(bg='#e1917f')
                TitFrame.config(bg='#e1917f')
                self.root.config(bg='#e1917f')
                DataFrame.config(bg='#e1917f')
                ButtonFrame.config(bg='#e1917f')
                self.lblfname.config(bg='#e1917f')
                self.txtfname.config(bg='#e1917f')
                self.lblmname.config(bg='#e1917f')
                self.txtmname.config(bg='#e1917f')
                self.lbllname.config(bg='#e1917f')
                self.txtlname.config(bg='#e1917f')
                self.lblmail.config(bg='#e1917f')
                self.txtmail.config(bg='#e1917f')
                self.lblmnumber.config(bg='#e1917f')
                self.txtmnumber.config(bg='#e1917f')
                self.lblwnumber.config(bg='#e1917f')
                self.txtwnumber.config(bg='#e1917f')
                self.lblbir.config(bg='#e1917f')
                self.txtbir.config(bg='#e1917f')
                DataFrameRight.config(bg='#e1917f')
                self.btnAddDate.config(bg='#e1917f')
                self.btnClear.config(bg='#e1917f')
                self.btnDelete.config(bg='#e1917f')
                self.btnDisplay.config(bg='#e1917f')
                self.btnExit.config(bg='#e1917f')
                self.btnUpdate.config(bg='#e1917f')
                btnBack.config(bg='#e1917f')
                btnTxt.config(bg='#e1917f')
                self.lblTit.config(bg='#e1917f')
                DataFrameLEFT.config(bg='#e1917f')
                DataFrameRight.config(bg='#e1917f')
                self.btnAddDate.config(bg='#e1917f')
                self.btnClear.config(bg='#e1917f')
                self.btnDelete.config(bg='#e1917f')
                self.btnDisplay.config(bg='#e1917f')
                self.btnExit.config(bg='#e1917f')
                self.btnUpdate.config(bg='#e1917f')
                btnBack.config(bg='#e1917f')
                btnTxt.config(bg='#e1917f')
                contactData.config(bg='#e1917f')

            def bckc9():
                MainFrame.config(bg='#c9f8fe')
                TitFrame.config(bg='#c9f8fe')
                self.root.config(bg='#c9f8fe')
                DataFrame.config(bg='#c9f8fe')
                ButtonFrame.config(bg='#c9f8fe')
                self.lblfname.config(bg='#c9f8fe')
                self.txtfname.config(bg='#c9f8fe')
                self.lblmname.config(bg='#c9f8fe')
                self.txtmname.config(bg='#c9f8fe')
                self.lbllname.config(bg='#c9f8fe')
                self.txtlname.config(bg='#c9f8fe')
                self.lblmail.config(bg='#c9f8fe')
                self.txtmail.config(bg='#c9f8fe')
                self.lblmnumber.config(bg='#c9f8fe')
                self.txtmnumber.config(bg='#c9f8fe')
                self.lblwnumber.config(bg='#c9f8fe')
                self.txtwnumber.config(bg='#c9f8fe')
                self.lblbir.config(bg='#c9f8fe')
                self.txtbir.config(bg='#c9f8fe')
                DataFrameRight.config(bg='#c9f8fe')
                self.btnAddDate.config(bg='#c9f8fe')
                self.btnClear.config(bg='#c9f8fe')
                self.btnDelete.config(bg='#c9f8fe')
                self.btnDisplay.config(bg='#c9f8fe')
                self.btnExit.config(bg='#c9f8fe')
                self.btnUpdate.config(bg='#c9f8fe')
                btnBack.config(bg='#c9f8fe')
                btnTxt.config(bg='#c9f8fe')
                self.lblTit.config(bg='#c9f8fe')
                DataFrameLEFT.config(bg='#c9f8fe')
                DataFrameRight.config(bg='#c9f8fe')
                self.btnAddDate.config(bg='#c9f8fe')
                self.btnClear.config(bg='#c9f8fe')
                self.btnDelete.config(bg='#c9f8fe')
                self.btnDisplay.config(bg='#c9f8fe')
                self.btnExit.config(bg='#c9f8fe')
                self.btnUpdate.config(bg='#c9f8fe')
                btnBack.config(bg='#c9f8fe')
                btnTxt.config(bg='#c9f8fe')
                contactData.config(bg='#c9f8fe')

            def bckff():
                MainFrame.config(bg='#ffc5e5')
                TitFrame.config(bg='#ffc5e5')
                self.root.config(bg='#ffc5e5')
                DataFrame.config(bg='#ffc5e5')
                ButtonFrame.config(bg='#ffc5e5')
                self.lblfname.config(bg='#ffc5e5')
                self.txtfname.config(bg='#ffc5e5')
                self.lblmname.config(bg='#ffc5e5')
                self.txtmname.config(bg='#ffc5e5')
                self.lbllname.config(bg='#ffc5e5')
                self.txtlname.config(bg='#ffc5e5')
                self.lblmail.config(bg='#ffc5e5')
                self.txtmail.config(bg='#ffc5e5')
                self.lblmnumber.config(bg='#ffc5e5')
                self.txtmnumber.config(bg='#ffc5e5')
                self.lblwnumber.config(bg='#ffc5e5')
                self.txtwnumber.config(bg='#ffc5e5')
                self.lblbir.config(bg='#ffc5e5')
                self.txtbir.config(bg='#ffc5e5')
                DataFrameRight.config(bg='#ffc5e5')
                self.btnAddDate.config(bg='#ffc5e5')
                self.btnClear.config(bg='#ffc5e5')
                self.btnDelete.config(bg='#ffc5e5')
                self.btnDisplay.config(bg='#ffc5e5')
                self.btnExit.config(bg='#ffc5e5')
                self.btnUpdate.config(bg='#ffc5e5')
                btnBack.config(bg='#ffc5e5')
                btnTxt.config(bg='#ffc5e5')
                self.lblTit.config(bg='#ffc5e5')
                DataFrameLEFT.config(bg='#ffc5e5')
                DataFrameRight.config(bg='#ffc5e5')
                self.btnAddDate.config(bg='#ffc5e5')
                self.btnClear.config(bg='#ffc5e5')
                self.btnDelete.config(bg='#ffc5e5')
                self.btnDisplay.config(bg='#ffc5e5')
                self.btnExit.config(bg='#ffc5e5')
                self.btnUpdate.config(bg='#ffc5e5')
                btnBack.config(bg='#ffc5e5')
                btnTxt.config(bg='#ffc5e5')
                contactData.config(bg='#ffc5e5')









            popupmsgback.wm_title('Background Color')
            label1 = tk.Label(popupmsgback,text='Background Themes',font='times',width=75,height=2)
            label1.pack(side=TOP)
            B1 = Button(popupmsgback, text='Okay',command=popupmsgback.destroy)
            B1.pack(side=BOTTOM)

            BBlue = Button(popupmsgback,bg='Light Blue',width=4,command=BackBlue)
            BBlue.pack(side=LEFT,pady=5)
            BBlue = Button(popupmsgback,bg='Dark Blue',width=4,command=BackDBlue)
            BBlue.pack(side=LEFT)
            BBlue = Button(popupmsgback, bg='cyan', width=4, command=Backcya)
            BBlue.pack(side=LEFT)
            Txtred = Button(popupmsgback,bg='Red',width=4,command=TxtRed)
            Txtred.pack(side=LEFT,pady=5)
            txtYel = Button(popupmsgback,bg='Orange',width=4,command=bckOr)
            txtYel.pack(side=LEFT)
            Txtgre = Button(popupmsgback,bg='Yellow',width=4,command=bckyel)
            Txtgre.pack(side=LEFT,pady=6)
            TxtOr = Button(popupmsgback,bg='Green',width=4,command=bckgre)
            TxtOr.pack(side=LEFT,pady=6)
            Txtblue = Button(popupmsgback, bg='Blue', width=4, command=bckxblue)
            Txtblue.pack(side=LEFT, pady=6)
            Txtdblue = Button(popupmsgback, bg='Dark Blue', width=4, command=bckdblue)
            Txtdblue.pack(side=LEFT, pady=6)
            Txtvio = Button(popupmsgback, bg='Violet', width=4, command=bckvio)
            Txtvio.pack(side=LEFT, pady=6)
            TxtMag = Button(popupmsgback, bg='Magenta', width=4, command=bckmag)
            TxtMag.pack(side=LEFT, pady=6)
            Txtpurp = Button(popupmsgback, bg='Purple', width=4, command=bckxpurp)
            Txtpurp.pack(side=LEFT, pady=6)
            Txtlgry = Button(popupmsgback, bg='Light Grey', width=4, command=bcklgry)
            Txtlgry.pack(side=LEFT, pady=6)
            Txtgry = Button(popupmsgback, bg='Dark Grey', width=4, command=bckdgray)
            Txtgry.pack(side=LEFT, pady=6)
            Txtdgry = Button(popupmsgback, bg='Grey', width=4, command=bckgry)
            Txtdgry.pack(side=LEFT, pady=6)
            Txtdgry = Button(popupmsgback, bg='#e1917f', width=4, command=bcke1)
            Txtdgry.pack(side=LEFT, pady=6)
            Txtdgry = Button(popupmsgback, bg='#c9f8fe', width=4, command=bckc9)
            Txtdgry.pack(side=LEFT, pady=6)
            Txtdgry = Button(popupmsgback, bg='#ffc5e5', width=4, command=bckff)
            Txtdgry.pack(side=LEFT, pady=6)






            popupmsgback.mainloop()

        def popupmsgtext():
            popuptext = tk.Tk()

            def TxtRed():
                self.lblfname.config(fg='red')
                self.txtfname.config(fg='red')
                self.lblmname.config(fg='red')
                self.txtmname.config(fg='red')
                self.lbllname.config(fg='red')
                self.txtlname.config(fg='red')
                self.lblmail.config(fg='red')
                self.txtmail.config(fg='red')
                self.lblmnumber.config(fg='red')
                self.txtmnumber.config(fg='red')
                self.lblwnumber.config(fg='red')
                self.txtwnumber.config(fg='red')
                self.lblbir.config(fg='red')
                self.txtbir.config(fg='red')
                DataFrameRight.config(fg='red')
                self.btnAddDate.config(fg='red')
                self.btnClear.config(fg='red')
                self.btnDelete.config(fg='red')
                self.btnDisplay.config(fg='red')
                self.btnExit.config(fg='red')
                self.btnUpdate.config(fg='red')
                btnBack.config(fg='red')
                btnTxt.config(fg='red')
                self.lblTit.config(fg='red')
                DataFrameLEFT.config(fg='red')
                DataFrameRight.config(fg='red')
                self.btnAddDate.config(fg='red')
                self.btnClear.config(fg='red')
                self.btnDelete.config(fg='red')
                self.btnDisplay.config(fg='red')
                self.btnExit.config(fg='red')
                self.btnUpdate.config(fg='red')
                btnBack.config(fg='red')
                btnTxt.config(fg='red')
                contactData.config(fg='red')

            def txtgre():
                self.lblfname.config(fg='green')
                self.txtfname.config(fg='green')
                self.lblmname.config(fg='green')
                self.txtmname.config(fg='green')
                self.lbllname.config(fg='green')
                self.txtlname.config(fg='green')
                self.lblmail.config(fg='green')
                self.txtmail.config(fg='green')
                self.lblmnumber.config(fg='green')
                self.txtmnumber.config(fg='green')
                self.lblwnumber.config(fg='green')
                self.txtwnumber.config(fg='green')
                self.lblbir.config(fg='green')
                self.txtbir.config(fg='green')
                DataFrameRight.config(fg='green')
                self.btnAddDate.config(fg='green')
                self.btnClear.config(fg='green')
                self.btnDelete.config(fg='green')
                self.btnDisplay.config(fg='green')
                self.btnExit.config(fg='green')
                self.btnUpdate.config(fg='green')
                btnBack.config(fg='green')
                btnTxt.config(fg='green')
                self.lblTit.config(fg='green')
                DataFrameLEFT.config(fg='green')
                DataFrameRight.config(fg='green')
                self.btnAddDate.config(fg='green')
                self.btnClear.config(fg='green')
                self.btnDelete.config(fg='green')
                self.btnDisplay.config(fg='green')
                self.btnExit.config(fg='green')
                self.btnUpdate.config(fg='green')
                btnBack.config(fg='green')
                btnTxt.config(fg='green')




            def txtyel():

                self.lblfname.config(fg='Yellow')
                self.txtfname.config(fg='Yellow')
                self.lblmname.config(fg='Yellow')
                self.txtmname.config(fg='Yellow')
                self.lbllname.config(fg='Yellow')
                self.txtlname.config(fg='Yellow')
                self.lblmail.config(fg='Yellow')
                self.txtmail.config(fg='Yellow')
                self.lblmnumber.config(fg='Yellow')
                self.txtmnumber.config(fg='Yellow')
                self.lblwnumber.config(fg='Yellow')
                self.txtwnumber.config(fg='Yellow')
                self.lblbir.config(fg='Yellow')
                self.txtbir.config(fg='Yellow')
                DataFrameRight.config(fg='Yellow')
                self.btnAddDate.config(fg='Yellow')
                self.btnClear.config(fg='Yellow')
                self.btnDelete.config(fg='Yellow')
                self.btnDisplay.config(fg='Yellow')
                self.btnExit.config(fg='Yellow')
                self.btnUpdate.config(fg='Yellow')
                btnBack.config(fg='Yellow')
                btnTxt.config(fg='Yellow')
                self.lblTit.config(fg='Yellow')
                DataFrameLEFT.config(fg='Yellow')
                DataFrameRight.config(fg='Yellow')
                self.btnAddDate.config(fg='Yellow')
                self.btnClear.config(fg='Yellow')
                self.btnDelete.config(fg='Yellow')
                self.btnDisplay.config(fg='Yellow')
                self.btnExit.config(fg='Yellow')
                self.btnUpdate.config(fg='Yellow')
                btnBack.config(fg='Yellow')
                btnTxt.config(fg='Yellow')
                contactData.config(fg='Yellow')

            def textOr():
                self.lblfname.config(fg='Orange')
                self.txtfname.config(fg='Orange')
                self.lblmname.config(fg='Orange')
                self.txtmname.config(fg='Orange')
                self.lbllname.config(fg='Orange')
                self.txtlname.config(fg='Orange')
                self.lblmail.config(fg='Orange')
                self.txtmail.config(fg='Orange')
                self.lblmnumber.config(fg='Orange')
                self.txtmnumber.config(fg='Orange')
                self.lblwnumber.config(fg='Orange')
                self.txtwnumber.config(fg='Orange')
                self.lblbir.config(fg='Orange')
                self.txtbir.config(fg='Orange')
                DataFrameRight.config(fg='Orange')
                self.btnAddDate.config(fg='Orange')
                self.btnClear.config(fg='Orange')
                self.btnDelete.config(fg='Orange')
                self.btnDisplay.config(fg='Orange')
                self.btnExit.config(fg='Orange')
                self.btnUpdate.config(fg='Orange')
                btnBack.config(fg='Orange')
                btnTxt.config(fg='Orange')
                self.lblTit.config(fg='Orange')
                DataFrameLEFT.config(fg='Orange')
                DataFrameRight.config(fg='Orange')
                self.btnAddDate.config(fg='Orange')
                self.btnClear.config(fg='Orange')
                self.btnDelete.config(fg='Orange')
                self.btnDisplay.config(fg='Orange')
                self.btnExit.config(fg='Orange')
                self.btnUpdate.config(fg='Orange')
                btnBack.config(fg='Orange')
                btnTxt.config(fg='Orange')
                contactData.config(fg='Orange')

            def txtlblu():
                self.lblfname.config(fg='Light Blue')
                self.txtfname.config(fg='Light Blue')
                self.lblmname.config(fg='Light Blue')
                self.txtmname.config(fg='Light Blue')
                self.lbllname.config(fg='Light Blue')
                self.txtlname.config(fg='Light Blue')
                self.lblmail.config(fg='Light Blue')
                self.txtmail.config(fg='Light Blue')
                self.lblmnumber.config(fg='Light Blue')
                self.txtmnumber.config(fg='Light Blue')
                self.lblwnumber.config(fg='Light Blue')
                self.txtwnumber.config(fg='Light Blue')
                self.lblbir.config(fg='Light Blue')
                self.txtbir.config(fg='Light Blue')
                DataFrameRight.config(fg='Light Blue')
                self.btnAddDate.config(fg='Light Blue')
                self.btnClear.config(fg='Light Blue')
                self.btnDelete.config(fg='Light Blue')
                self.btnDisplay.config(fg='Light Blue')
                self.btnExit.config(fg='Light Blue')
                self.btnUpdate.config(fg='Light Blue')
                btnBack.config(fg='Light Blue')
                btnTxt.config(fg='Light Blue')
                self.lblTit.config(fg='Light Blue')
                DataFrameLEFT.config(fg='Light Blue')
                DataFrameRight.config(fg='Light Blue')
                self.btnAddDate.config(fg='Light Blue')
                self.btnClear.config(fg='Light Blue')
                self.btnDelete.config(fg='Light Blue')
                self.btnDisplay.config(fg='Light Blue')
                self.btnExit.config(fg='Light Blue')
                self.btnUpdate.config(fg='Light Blue')
                btnBack.config(fg='Light Blue')
                btnTxt.config(fg='Light Blue')
                contactData.config(fg='Light Blue')

            def txtca():
                self.lblfname.config(fg='Cyan')
                self.txtfname.config(fg='Cyan')
                self.lblmname.config(fg='Cyan')
                self.txtmname.config(fg='Cyan')
                self.lbllname.config(fg='Cyan')
                self.txtlname.config(fg='Cyan')
                self.lblmail.config(fg='Cyan')
                self.txtmail.config(fg='Cyan')
                self.lblmnumber.config(fg='Cyan')
                self.txtmnumber.config(fg='Cyan')
                self.lblwnumber.config(fg='Cyan')
                self.txtwnumber.config(fg='Cyan')
                self.lblbir.config(fg='Cyan')
                self.txtbir.config(fg='Cyan')
                DataFrameRight.config(fg='Cyan')
                self.btnAddDate.config(fg='Cyan')
                self.btnClear.config(fg='Cyan')
                self.btnDelete.config(fg='Cyan')
                self.btnDisplay.config(fg='Cyan')
                self.btnExit.config(fg='Cyan')
                self.btnUpdate.config(fg='Cyan')
                btnBack.config(fg='Cyan')
                btnTxt.config(fg='Cyan')
                self.lblTit.config(fg='Cyan')
                DataFrameLEFT.config(fg='Cyan')
                DataFrameRight.config(fg='Cyan')
                self.btnAddDate.config(fg='Cyan')
                self.btnClear.config(fg='Cyan')
                self.btnDelete.config(fg='Cyan')
                self.btnDisplay.config(fg='Cyan')
                self.btnExit.config(fg='Cyan')
                self.btnUpdate.config(fg='Cyan')
                btnBack.config(fg='Cyan')
                btnTxt.config(fg='Cyan')
                contactData.config(fg='Cyan')

            def txtblue():
                self.lblfname.config(fg='Blue')
                self.txtfname.config(fg='Blue')
                self.lblmname.config(fg='Blue')
                self.txtmname.config(fg='Blue')
                self.lbllname.config(fg='Blue')
                self.txtlname.config(fg='Blue')
                self.lblmail.config(fg='Blue')
                self.txtmail.config(fg='Blue')
                self.lblmnumber.config(fg='Blue')
                self.txtmnumber.config(fg='Blue')
                self.lblwnumber.config(fg='Blue')
                self.txtwnumber.config(fg='Blue')
                self.lblbir.config(fg='Blue')
                self.txtbir.config(fg='Blue')
                DataFrameRight.config(fg='Blue')
                self.btnAddDate.config(fg='Blue')
                self.btnClear.config(fg='Blue')
                self.btnDelete.config(fg='Blue')
                self.btnDisplay.config(fg='Blue')
                self.btnExit.config(fg='Blue')
                self.btnUpdate.config(fg='Blue')
                btnBack.config(fg='Blue')
                btnTxt.config(fg='Blue')
                self.lblTit.config(fg='Blue')
                DataFrameLEFT.config(fg='Blue')
                DataFrameRight.config(fg='Blue')
                self.btnAddDate.config(fg='Blue')
                self.btnClear.config(fg='Blue')
                self.btnDelete.config(fg='Blue')
                self.btnDisplay.config(fg='Blue')
                self.btnExit.config(fg='Blue')
                self.btnUpdate.config(fg='Blue')
                btnBack.config(fg='Blue')
                btnTxt.config(fg='Blue')
                contactData.config(fg='Blue')

            def txtdblue():
                self.lblfname.config(fg='Dark Blue')
                self.txtfname.config(fg='Dark Blue')
                self.lblmname.config(fg='Dark Blue')
                self.txtmname.config(fg='Dark Blue')
                self.lbllname.config(fg='Dark Blue')
                self.txtlname.config(fg='Dark Blue')
                self.lblmail.config(fg='Dark Blue')
                self.txtmail.config(fg='Dark Blue')
                self.lblmnumber.config(fg='Dark Blue')
                self.txtmnumber.config(fg='Dark Blue')
                self.lblwnumber.config(fg='Dark Blue')
                self.txtwnumber.config(fg='Dark Blue')
                self.lblbir.config(fg='Dark Blue')
                self.txtbir.config(fg='Dark Blue')
                DataFrameRight.config(fg='Dark Blue')
                self.btnAddDate.config(fg='Dark Blue')
                self.btnClear.config(fg='Dark Blue')
                self.btnDelete.config(fg='Dark Blue')
                self.btnDisplay.config(fg='Dark Blue')
                self.btnExit.config(fg='Dark Blue')
                self.btnUpdate.config(fg='Dark Blue')
                btnBack.config(fg='Dark Blue')
                btnTxt.config(fg='Dark Blue')
                self.lblTit.config(fg='Dark Blue')
                DataFrameLEFT.config(fg='Dark Blue')
                DataFrameRight.config(fg='Dark Blue')
                self.btnAddDate.config(fg='Dark Blue')
                self.btnClear.config(fg='Dark Blue')
                self.btnDelete.config(fg='Dark Blue')
                self.btnDisplay.config(fg='Dark Blue')
                self.btnExit.config(fg='Dark Blue')
                self.btnUpdate.config(fg='Dark Blue')
                btnBack.config(fg='Dark Blue')
                btnTxt.config(fg='Dark Blue')
                contactData.config(fg='Dark Blue')

            def txtvio():
                self.lblfname.config(fg='Violet')
                self.txtfname.config(fg='Violet')
                self.lblmname.config(fg='Violet')
                self.txtmname.config(fg='Violet')
                self.lbllname.config(fg='Violet')
                self.txtlname.config(fg='Violet')
                self.lblmail.config(fg='Violet')
                self.txtmail.config(fg='Violet')
                self.lblmnumber.config(fg='Violet')
                self.txtmnumber.config(fg='Violet')
                self.lblwnumber.config(fg='Violet')
                self.txtwnumber.config(fg='Violet')
                self.lblbir.config(fg='Violet')
                self.txtbir.config(fg='Violet')
                DataFrameRight.config(fg='Violet')
                self.btnAddDate.config(fg='Violet')
                self.btnClear.config(fg='Violet')
                self.btnDelete.config(fg='Violet')
                self.btnDisplay.config(fg='Violet')
                self.btnExit.config(fg='Violet')
                self.btnUpdate.config(fg='Violet')
                btnBack.config(fg='Violet')
                btnTxt.config(fg='Violet')
                self.lblTit.config(fg='Violet')
                DataFrameLEFT.config(fg='Violet')
                DataFrameRight.config(fg='Violet')
                self.btnAddDate.config(fg='Violet')
                self.btnClear.config(fg='Violet')
                self.btnDelete.config(fg='Violet')
                self.btnDisplay.config(fg='Violet')
                self.btnExit.config(fg='Violet')
                self.btnUpdate.config(fg='Violet')
                btnBack.config(fg='Violet')
                btnTxt.config(fg='Violet')
                contactData.config(fg='Violet')

            def txtmag():
                self.lblfname.config(fg='Magenta')
                self.txtfname.config(fg='Magenta')
                self.lblmname.config(fg='Magenta')
                self.txtmname.config(fg='Magenta')
                self.lbllname.config(fg='Magenta')
                self.txtlname.config(fg='Magenta')
                self.lblmail.config(fg='Magenta')
                self.txtmail.config(fg='Magenta')
                self.lblmnumber.config(fg='Magenta')
                self.txtmnumber.config(fg='Magenta')
                self.lblwnumber.config(fg='Magenta')
                self.txtwnumber.config(fg='Magenta')
                self.lblbir.config(fg='Magenta')
                self.txtbir.config(fg='Magenta')
                DataFrameRight.config(fg='Magenta')
                self.btnAddDate.config(fg='Magenta')
                self.btnClear.config(fg='Magenta')
                self.btnDelete.config(fg='Magenta')
                self.btnDisplay.config(fg='Magenta')
                self.btnExit.config(fg='Magenta')
                self.btnUpdate.config(fg='Magenta')
                btnBack.config(fg='Magenta')
                btnTxt.config(fg='Magenta')
                self.lblTit.config(fg='Magenta')
                DataFrameLEFT.config(fg='Magenta')
                DataFrameRight.config(fg='Magenta')
                self.btnAddDate.config(fg='Magenta')
                self.btnClear.config(fg='Magenta')
                self.btnDelete.config(fg='Magenta')
                self.btnDisplay.config(fg='Magenta')
                self.btnExit.config(fg='Magenta')
                self.btnUpdate.config(fg='Magenta')
                btnBack.config(fg='Magenta')
                btnTxt.config(fg='Magenta')
                contactData.config(fg='Magenta')

            def txtpurp():
                self.lblfname.config(fg='Purple')
                self.txtfname.config(fg='Purple')
                self.lblmname.config(fg='Purple')
                self.txtmname.config(fg='Purple')
                self.lbllname.config(fg='Purple')
                self.txtlname.config(fg='Purple')
                self.lblmail.config(fg='Purple')
                self.txtmail.config(fg='Purple')
                self.lblmnumber.config(fg='Purple')
                self.txtmnumber.config(fg='Purple')
                self.lblwnumber.config(fg='Purple')
                self.txtwnumber.config(fg='Purple')
                self.lblbir.config(fg='Purple')
                self.txtbir.config(fg='Purple')
                DataFrameRight.config(fg='Purple')
                self.btnAddDate.config(fg='Purple')
                self.btnClear.config(fg='Purple')
                self.btnDelete.config(fg='Purple')
                self.btnDisplay.config(fg='Purple')
                self.btnExit.config(fg='Purple')
                self.btnUpdate.config(fg='Purple')
                btnBack.config(fg='Purple')
                btnTxt.config(fg='Purple')
                self.lblTit.config(fg='Purple')
                DataFrameLEFT.config(fg='Purple')
                DataFrameRight.config(fg='Purple')
                self.btnAddDate.config(fg='Purple')
                self.btnClear.config(fg='Purple')
                self.btnDelete.config(fg='Purple')
                self.btnDisplay.config(fg='Purple')
                self.btnExit.config(fg='Purple')
                self.btnUpdate.config(fg='Purple')
                btnBack.config(fg='Purple')
                btnTxt.config(fg='Purple')
                contactData.config(fg='Purple')

            def txtlgry():
                self.lblfname.config(fg='Light Grey')
                self.txtfname.config(fg='Light Grey')
                self.lblmname.config(fg='Light Grey')
                self.txtmname.config(fg='Light Grey')
                self.lbllname.config(fg='Light Grey')
                self.txtlname.config(fg='Light Grey')
                self.lblmail.config(fg='Light Grey')
                self.txtmail.config(fg='Light Grey')
                self.lblmnumber.config(fg='Light Grey')
                self.txtmnumber.config(fg='Light Grey')
                self.lblwnumber.config(fg='Light Grey')
                self.txtwnumber.config(fg='Light Grey')
                self.lblbir.config(fg='Light Grey')
                self.txtbir.config(fg='Light Grey')
                DataFrameRight.config(fg='Light Grey')
                self.btnAddDate.config(fg='Light Grey')
                self.btnClear.config(fg='Light Grey')
                self.btnDelete.config(fg='Light Grey')
                self.btnDisplay.config(fg='Light Grey')
                self.btnExit.config(fg='Light Grey')
                self.btnUpdate.config(fg='Light Grey')
                btnBack.config(fg='Light Grey')
                btnTxt.config(fg='Light Grey')
                self.lblTit.config(fg='Light Grey')
                DataFrameLEFT.config(fg='Light Grey')
                DataFrameRight.config(fg='Light Grey')
                self.btnAddDate.config(fg='Light Grey')
                self.btnClear.config(fg='Light Grey')
                self.btnDelete.config(fg='Light Grey')
                self.btnDisplay.config(fg='Light Grey')
                self.btnExit.config(fg='Light Grey')
                self.btnUpdate.config(fg='Light Grey')
                btnBack.config(fg='Light Grey')
                btnTxt.config(fg='Light Grey')
                contactData.config(fg='Light Grey')

            def txtgry():
                self.lblfname.config(fg='Grey')
                self.txtfname.config(fg='Grey')
                self.lblmname.config(fg='Grey')
                self.txtmname.config(fg='Grey')
                self.lbllname.config(fg='Grey')
                self.txtlname.config(fg='Grey')
                self.lblmail.config(fg='Grey')
                self.txtmail.config(fg='Grey')
                self.lblmnumber.config(fg='Grey')
                self.txtmnumber.config(fg='Grey')
                self.lblwnumber.config(fg='Grey')
                self.txtwnumber.config(fg='Grey')
                self.lblbir.config(fg='Grey')
                self.txtbir.config(fg='Grey')
                DataFrameRight.config(fg='Grey')
                self.btnAddDate.config(fg='Grey')
                self.btnClear.config(fg='Grey')
                self.btnDelete.config(fg='Grey')
                self.btnDisplay.config(fg='Grey')
                self.btnExit.config(fg='Grey')
                self.btnUpdate.config(fg='Grey')
                btnBack.config(fg='Grey')
                btnTxt.config(fg='Grey')
                self.lblTit.config(fg='Grey')
                DataFrameLEFT.config(fg='Grey')
                DataFrameRight.config(fg='Grey')
                self.btnAddDate.config(fg='Grey')
                self.btnClear.config(fg='Grey')
                self.btnDelete.config(fg='Grey')
                self.btnDisplay.config(fg='Grey')
                self.btnExit.config(fg='Grey')
                self.btnUpdate.config(fg='Grey')
                btnBack.config(fg='Grey')
                btnTxt.config(fg='Grey')
                contactData.config(fg='Grey')

            def txtdgray():
                self.lblfname.config(fg='Dark Grey')
                self.txtfname.config(fg='Dark Grey')
                self.lblmname.config(fg='Dark Grey')
                self.txtmname.config(fg='Dark Grey')
                self.lbllname.config(fg='Dark Grey')
                self.txtlname.config(fg='Dark Grey')
                self.lblmail.config(fg='Dark Grey')
                self.txtmail.config(fg='Dark Grey')
                self.lblmnumber.config(fg='Dark Grey')
                self.txtmnumber.config(fg='Dark Grey')
                self.lblwnumber.config(fg='Dark Grey')
                self.txtwnumber.config(fg='Dark Grey')
                self.lblbir.config(fg='Dark Grey')
                self.txtbir.config(fg='Dark Grey')
                DataFrameRight.config(fg='Dark Grey')
                self.btnAddDate.config(fg='Dark Grey')
                self.btnClear.config(fg='Dark Grey')
                self.btnDelete.config(fg='Dark Grey')
                self.btnDisplay.config(fg='Dark Grey')
                self.btnExit.config(fg='Dark Grey')
                self.btnUpdate.config(fg='Dark Grey')
                btnBack.config(fg='Dark Grey')
                btnTxt.config(fg='Dark Grey')
                self.lblTit.config(fg='Dark Grey')
                DataFrameLEFT.config(fg='Dark Grey')
                DataFrameRight.config(fg='Dark Grey')
                self.btnAddDate.config(fg='Dark Grey')
                self.btnClear.config(fg='Dark Grey')
                self.btnDelete.config(fg='Dark Grey')
                self.btnDisplay.config(fg='Dark Grey')
                self.btnExit.config(fg='Dark Grey')
                self.btnUpdate.config(fg='Dark Grey')
                btnBack.config(fg='Dark Grey')
                btnTxt.config(fg='Dark Grey')
                contactData.config(fg='Dark Grey')

            def bcke1():
                self.lblfname.config(fg='#e1917f')
                self.txtfname.config(fg='#e1917f')
                self.lblmname.config(fg='#e1917f')
                self.txtmname.config(fg='#e1917f')
                self.lbllname.config(fg='#e1917f')
                self.txtlname.config(fg='#e1917f')
                self.lblmail.config(fg='#e1917f')
                self.txtmail.config(fg='#e1917f')
                self.lblmnumber.config(fg='#e1917f')
                self.txtmnumber.config(fg='#e1917f')
                self.lblwnumber.config(fg='#e1917f')
                self.txtwnumber.config(fg='#e1917f')
                self.lblbir.config(fg='#e1917f')
                self.txtbir.config(fg='#e1917f')
                DataFrameRight.config(fg='#e1917f')
                self.btnAddDate.config(fg='#e1917f')
                self.btnClear.config(fg='#e1917f')
                self.btnDelete.config(fg='#e1917f')
                self.btnDisplay.config(fg='#e1917f')
                self.btnExit.config(fg='#e1917f')
                self.btnUpdate.config(fg='#e1917f')
                btnBack.config(fg='#e1917f')
                btnTxt.config(fg='#e1917f')
                self.lblTit.config(fg='#e1917f')
                DataFrameLEFT.config(fg='#e1917f')
                DataFrameRight.config(fg='#e1917f')
                self.btnAddDate.config(fg='#e1917f')
                self.btnClear.config(fg='#e1917f')
                self.btnDelete.config(fg='#e1917f')
                self.btnDisplay.config(fg='#e1917f')
                self.btnExit.config(fg='#e1917f')
                self.btnUpdate.config(fg='#e1917f')
                btnBack.config(fg='#e1917f')
                btnTxt.config(fg='#e1917f')
                contactData.config(fg='#e1917f')

            def bckc9():
                self.lblfname.config(fg='#c9f8fe')
                self.txtfname.config(fg='#c9f8fe')
                self.lblmname.config(fg='#c9f8fe')
                self.txtmname.config(fg='#c9f8fe')
                self.lbllname.config(fg='#c9f8fe')
                self.txtlname.config(fg='#c9f8fe')
                self.lblmail.config(fg='#c9f8fe')
                self.txtmail.config(fg='#c9f8fe')
                self.lblmnumber.config(fg='#c9f8fe')
                self.txtmnumber.config(fg='#c9f8fe')
                self.lblwnumber.config(fg='#c9f8fe')
                self.txtwnumber.config(fg='#c9f8fe')
                self.lblbir.config(fg='#c9f8fe')
                self.txtbir.config(fg='#c9f8fe')
                DataFrameRight.config(fg='#c9f8fe')
                self.btnAddDate.config(fg='#c9f8fe')
                self.btnClear.config(fg='#c9f8fe')
                self.btnDelete.config(fg='#c9f8fe')
                self.btnDisplay.config(fg='#c9f8fe')
                self.btnExit.config(fg='#c9f8fe')
                self.btnUpdate.config(fg='#c9f8fe')
                btnBack.config(fg='#c9f8fe')
                btnTxt.config(fg='#c9f8fe')
                self.lblTit.config(fg='#c9f8fe')
                DataFrameLEFT.config(fg='#c9f8fe')
                DataFrameRight.config(fg='#c9f8fe')
                self.btnAddDate.config(fg='#c9f8fe')
                self.btnClear.config(fg='#c9f8fe')
                self.btnDelete.config(fg='#c9f8fe')
                self.btnDisplay.config(fg='#c9f8fe')
                self.btnExit.config(fg='#c9f8fe')
                self.btnUpdate.config(fg='#c9f8fe')
                btnBack.config(fg='#c9f8fe')
                btnTxt.config(fg='#c9f8fe')
                contactData.config(fg='#c9f8fe')

            def bckff():
                self.lblfname.config(fg='#ffc5e5')
                self.txtfname.config(fg='#ffc5e5')
                self.lblmname.config(fg='#ffc5e5')
                self.txtmname.config(fg='#ffc5e5')
                self.lbllname.config(fg='#ffc5e5')
                self.txtlname.config(fg='#ffc5e5')
                self.lblmail.config(fg='#ffc5e5')
                self.txtmail.config(fg='#ffc5e5')
                self.lblmnumber.config(fg='#ffc5e5')
                self.txtmnumber.config(fg='#ffc5e5')
                self.lblwnumber.config(fg='#ffc5e5')
                self.txtwnumber.config(fg='#ffc5e5')
                self.lblbir.config(fg='#ffc5e5')
                self.txtbir.config(fg='#ffc5e5')
                DataFrameRight.config(fg='#ffc5e5')
                self.btnAddDate.config(fg='#ffc5e5')
                self.btnClear.config(fg='#ffc5e5')
                self.btnDelete.config(fg='#ffc5e5')
                self.btnDisplay.config(fg='#ffc5e5')
                self.btnExit.config(fg='#ffc5e5')
                self.btnUpdate.config(fg='#ffc5e5')
                btnBack.config(fg='#ffc5e5')
                btnTxt.config(fg='#ffc5e5')
                self.lblTit.config(fg='#ffc5e5')
                DataFrameLEFT.config(fg='#ffc5e5')
                DataFrameRight.config(fg='#ffc5e5')
                self.btnAddDate.config(fg='#ffc5e5')
                self.btnClear.config(fg='#ffc5e5')
                self.btnDelete.config(fg='#ffc5e5')
                self.btnDisplay.config(fg='#ffc5e5')
                self.btnExit.config(fg='#ffc5e5')
                self.btnUpdate.config(fg='#ffc5e5')
                btnBack.config(fg='#ffc5e5')
                btnTxt.config(fg='#ffc5e5')
                contactData.config(fg='#ffc5e5')








            popuptext.wm_title('Text/ForeGround color')
            label1 = tk.Label(popuptext,text='Background Themes',font='times',width=75,height=2)
            label1.pack(side=TOP)
            B1 = Button(popuptext, text='Okay',command=popuptext.destroy)
            B1.pack(side=BOTTOM)

            BBlue = Button(popuptext, bg='Light Blue', width=4, command=txtlblu)
            BBlue.pack(side=LEFT, pady=5)
            BBlue = Button(popuptext, bg='Dark Blue', width=4, command=txtdblue)
            BBlue.pack(side=LEFT)
            BBlue = Button(popuptext, bg='cyan', width=4, command=txtca)
            BBlue.pack(side=LEFT)
            Txtred = Button(popuptext, bg='Red', width=4, command=TxtRed)
            Txtred.pack(side=LEFT, pady=5)
            txtYel = Button(popuptext, bg='Orange', width=4, command=textOr)
            txtYel.pack(side=LEFT)
            Txtgre = Button(popuptext, bg='yellow', width=4, command=txtyel)
            Txtgre.pack(side=LEFT, pady=6)
            TxtOr = Button(popuptext, bg='Green', width=4, command=txtgre)
            TxtOr.pack(side=LEFT, pady=6)
            Txtblue = Button(popuptext, bg='Blue', width=4, command=txtblue)
            Txtblue.pack(side=LEFT, pady=6)
            Txtdblue = Button(popuptext, bg='Dark Blue', width=4, command=txtdblue)
            Txtdblue.pack(side=LEFT, pady=6)
            Txtvio = Button(popuptext, bg='Violet', width=4, command=txtvio)
            Txtvio.pack(side=LEFT, pady=6)
            TxtMag = Button(popuptext, bg='Magenta', width=4, command=txtmag)
            TxtMag.pack(side=LEFT, pady=6)
            Txtpurp = Button(popuptext, bg='Purple', width=4, command=txtpurp)
            Txtpurp.pack(side=LEFT, pady=6)
            Txtlgry = Button(popuptext, bg='Light Grey', width=4, command=txtlgry)
            Txtlgry.pack(side=LEFT, pady=6)
            Txtgry = Button(popuptext, bg='Dark Grey', width=4, command=txtdgray)
            Txtgry.pack(side=LEFT, pady=6)
            Txtdgry = Button(popuptext, bg='Grey', width=4, command=txtgry)
            Txtdgry.pack(side=LEFT, pady=6)
            Txtdgry = Button(popuptext, bg='#e1917f', width=4, command=bcke1)
            Txtdgry.pack(side=LEFT, pady=6)
            Txtdgry = Button(popuptext, bg='#c9f8fe', width=4, command=bckc9)
            Txtdgry.pack(side=LEFT, pady=6)
            Txtdgry = Button(popuptext, bg='#ffc5e5', width=4, command=bckff)
            Txtdgry.pack(side=LEFT, pady=6)


        #Frames
        MainFrame = Frame(self.root, bg="#d4f1ff")
        MainFrame.grid()

        TitFrame = Frame(MainFrame, bd=2, padx=54, pady=8, bg="Ghost White",relief=RIDGE)
        TitFrame.pack(side=TOP)

        self.lblTit = Label(TitFrame,font=('Comfortaa', 47,'bold'),text='Contacts',bg='Ghost White')
        self.lblTit.grid()

        ButtonFrame = Frame(MainFrame, bd=2,width=1350,height=70,padx=18,pady=10,bg="#d4f1ff",relief=RIDGE)
        ButtonFrame.pack()

        DataFrame =Frame(MainFrame, bd=3, width=1300, height=400, padx=20, pady=20, relief=RIDGE, bg="#d4f1ff")
        DataFrame.pack(side=BOTTOM)

        DataFrameLEFT =LabelFrame(DataFrame, bd=1,width=1000,height=14,padx=20, relief=RIDGE, bg='Ghost White',
                                   font=('Comfortaa', 20,'bold'), text='Contact Information\n')
        DataFrameLEFT.pack(side=LEFT)

        DataFrameRight =LabelFrame(DataFrame, bd=1,width=450,height=300,padx=31,pady=3,relief=RIDGE, bg='Ghost White',
                                   font=('Comfortaa', 20,'bold'), text='Contact Details\n')
        DataFrameRight.pack(padx=100)

        #Widgets
        self.lblfname = Label(DataFrameLEFT,font=('Courier',20,'bold'),text='First Name',padx=2,pady=2,bg='Ghost White')
        self.lblfname.grid(row=0,column=0, sticky=W)
        self.txtfname = Entry(DataFrameLEFT, font=('Courier', 20, 'bold'), textvariable=fname,width=39,bg='Ghost White')
        self.txtfname.grid(row=0, column=1)
#
        self.lblmname = Label(DataFrameLEFT,font=('Courier',20,'bold'),text='Middle Name',padx=2,pady=2,bg='Ghost White')
        self.lblmname.grid(row=1,column=0, sticky=W)
        self.txtmname = Entry(DataFrameLEFT, font=('Courier',20, 'bold'), textvariable=mname, width=39,bg='Ghost White')
        self.txtmname.grid(row=1, column=1)

        self.lbllname = Label(DataFrameLEFT,font=('Courier',20,'bold'),text='Last Name',padx=2,pady=2,bg='Ghost White')
        self.lbllname.grid(row=2,column=0, sticky=W)
        self.txtlname = Entry(DataFrameLEFT, font=('Courier',20, 'bold'), textvariable=lname, width=39,bg='Ghost White')
        self.txtlname.grid(row=2, column=1)

        self.lblmail = Label(DataFrameLEFT,font=('Courier',20,'bold'),text='E-Mail',padx=2,pady=2,bg='Ghost White')
        self.lblmail.grid(row=3,column=0, sticky=W)
        self.txtmail = Entry(DataFrameLEFT, font=('Courier', 20, 'bold'), textvariable=mail,width=39,bg='Ghost White')
        self.txtmail.grid(row=3, column=1)
#
        self.lblmnumber = Label(DataFrameLEFT,font=('Courier',20,'bold'),text='Mobile Number',padx=2,pady=2,
                                bg='Ghost White')
        self.lblmnumber.grid(row=4,column=0, sticky=W)
        self.txtmnumber = Entry(DataFrameLEFT, font=('Courier',20, 'bold'), textvariable=mnumber, width=39,
                                bg='Ghost White')
        self.txtmnumber.grid(row=4, column=1)

        self.lblwnumber = Label(DataFrameLEFT,font=('Courier',20,'bold'),text='Work Number',padx=2,pady=2,
                                bg='Ghost White')
        self.lblwnumber.grid(row=5,column=0, sticky=W)
        self.txtwnumber = Entry(DataFrameLEFT, font=('Courier',20, 'bold'), textvariable=wnumber, width=39,
                                bg='Ghost White')
        self.txtwnumber.grid(row=5, column=1)

        self.lblbir = Label(DataFrameLEFT,font=('Courier',20,'bold'),text='Birthday',padx=2,pady=2,bg='Ghost White')
        self.lblbir.grid(row=6,column=0, sticky=W)
        self.txtbir = Entry(DataFrameLEFT, font=('Courier',20, 'bold'), textvariable=dob, width=39,bg='Ghost White')
        self.txtbir.grid(row=6, column=1)

        #Listbox

        scrollbar = Scrollbar(DataFrameRight)
        scrollbar.grid(row=0, column=1, sticky='ns')

        contactData = Listbox(DataFrameRight, width=51, height=14, font=('Comfortaa', 12, 'bold'),
                              yscrollcommand=scrollbar.set)
        contactData.bind('<<ListboxSelect>>', ContactRec)
        contactData.grid(row=0,column=0,padx=10)
        scrollbar.config(command=contactData.yview)


        #Button Widget
        self.btnAddDate = Button(ButtonFrame, text="Add New", font=('Comfortaa', 20, 'bold'),height=1,width=10,
                                 bd=4, command=addData)
        self.btnAddDate.grid(row=0, column=0)

        self.btnDisplay = Button(ButtonFrame, text="Display", font=('Comfortaa', 20, 'bold'),height=1,width=10,bd=4,
                                 command=DisplayData)
        self.btnDisplay.grid(row=0, column=1)

        self.btnClear=Button(ButtonFrame,text="Clear",font=('Comfortaa',20,'bold'),height=1,width=10,bd=4,
                             command=clearData)
        self.btnClear.grid(row=0, column=2)

        self.btnDelete = Button(ButtonFrame, text="Delete", font=('Comfortaa', 20, 'bold'),height=1,width=10,
                                bd=4, command=DeleteDate)
        self.btnDelete.grid(row=0, column=3)

        self.btnUpdate = Button(ButtonFrame, text="Update", font=('Comfortaa', 20, 'bold'),height=1,width=10,bd=4,
                                command=update)
        self.btnUpdate.grid(row=0, column=5)

        self.btnExit=Button(ButtonFrame,text="Exit",font=('Comfortaa',20,'bold'),height=1,width=10,bd=4,command=iExit)
        self.btnExit.grid(row=0, column=6)

        btnBack=Button(root, text='Background Color',font=('Comfortaa',12,'bold'),height=1,width=20,bd=4,
                       command=popupmsgback)
        btnBack.place(x=25,y=25)

        btnTxt=Button(root, text='Text Color',font=('Comfortaa',12,'bold'),height=1,width=20,bd=4,
                       command=popupmsgtext)
        btnTxt.place(x=1400,y=25)








if __name__=='__main__':
    root = Tk()
    application = Contact(root)
    root.mainloop()